[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["build/compile_commands.json", ".clangd"]
command = "clangd"

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json", "tsconfig.json"]
command = "typescript-language-server"
args = ["--stdio"]


