
# plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# install LSP
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
}

hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp|java) %{
    lsp-enable-window
}



# fzf
plug "andreyorst/fzf.kak"
# Ctrl+P: find and open file in project
map global normal <c-p> ': fzf-mode<ret>f'
# F12: goto symbol
map global normal <F12> ': fzf-mode<ret>g'
# Ctrl+Shift+F: find in files
map global normal <c-s-f> ': fzf-mode<ret>g'

# alt-<left>/<right>: buffer navigation
map global normal <a-left> ': buffer-previous<ret>'
map global normal <a-right> ': buffer-next<ret>'

# line numbers
add-highlighter global/ number-lines

# tabs
set-option global tabstop 4
set-option global indentwidth 4
# tab key does indent/unindent
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'

# use down/up arrows for completion
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <down> <c-n>
        map window insert <up> <c-p>
        hook -once -always window InsertCompletionHide .* %{
            map window insert <down> <down>
            map window insert <up> <up>
        }
    }
}

# theme
colorscheme lucius
